### ISSUE TITLE
Mysterious number exception - Debug build?

### ISSUE THREAD

**Issue by ochafik** [openscad/openscad-wasm#2]
Thank you so much for the *amazing* job!

Most models ([example](https://files.openscad.org/examples/Basics/CSG.html)) seem to just explode with an exception (just throwing a number really), which I don't know how to debug. Could you help with instructions to produce a debug build? I naively tried to change `-CMAKE_BUILD_TYPE=Release` and didn't get very far. Also, I've tried increasing the size of the wasmMemory but didn't help.

**Edit**: @t-paul has kindly posted Debug & RelWithDebugInfo builds [here](http://files.openscad.org/wasm/).

FYI I've wrapped your build with an editor & stl viewer here: https://ochafik.com/openscad (here's a [deep-link to a model that explodes](https://ochafik.com/openscad/#%7B%22source%22%3A%7B%22name%22%3A%22input.stl%22%2C%22content%22%3A%22%5Cn%2F%2F%20CSG.scad%20-%20Basic%20example%20of%20CSG%20usage%5Cn%5Cntranslate(%5B-24%2C0%2C0%5D)%20%7B%5Cn%20%20%20%20union()%20%7B%5Cn%20%20%20%20%20%20%20%20cube(15%2C%20center%3Dtrue)%3B%5Cn%20%20%20%20%20%20%20%20sphere(10)%3B%5Cn%20%20%20%20%7D%5Cn%7D%5Cn%5Cnintersection()%20%7B%5Cn%20%20%20%20cube(15%2C%20center%3Dtrue)%3B%5Cn%20%20%20%20sphere(10)%3B%5Cn%7D%5Cn%5Cntranslate(%5B24%2C0%2C0%5D)%20%7B%5Cn%20%20%20%20difference()%20%7B%5Cn%20%20%20%20%20%20%20%20cube(15%2C%20center%3Dtrue)%3B%5Cn%20%20%20%20%20%20%20%20sphere(10)%3B%5Cn%20%20%20%20%7D%5Cn%7D%5Cn%5Cnecho(version%3Dversion())%3B%5Cn%2F%2F%20Written%20by%20Marius%20Kintel%20%3Cmarius%40kintel.net%3E%5Cn%2F%2F%5Cn%2F%2F%20To%20the%20extent%20possible%20under%20law%2C%20the%20author(s)%20have%20dedicated%20all%5Cn%2F%2F%20copyright%20and%20related%20and%20neighboring%20rights%20to%20this%20software%20to%20the%5Cn%2F%2F%20public%20domain%20worldwide.%20This%20software%20is%20distributed%20without%20any%5Cn%2F%2F%20warranty.%5Cn%2F%2F%5Cn%2F%2F%20You%20should%20have%20received%20a%20copy%20of%20the%20CC0%20Public%20Domain%5Cn%2F%2F%20Dedication%20along%20with%20this%20software.%5Cn%2F%2F%20If%20not%2C%20see%20%3Chttp%3A%2F%2Fcreativecommons.org%2Fpublicdomain%2Fzero%2F1.0%2F%3E.%5Cn%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%7D%2C%22autorender%22%3Atrue%2C%22autoparse%22%3Atrue%2C%22maximumMegabytes%22%3A1024%2C%22features%22%3A%5B%5D%2C%22showExp%22%3Atrue%2C%22camera%22%3Anull%7D))

![Screen Shot 2022-02-19 at 16 17 17](https://user-images.githubusercontent.com/273860/154857385-9c459466-62f9-4845-86db-608bf37176f2.png)

**Comment by DSchroer** [comment]
Hey. I'm quite curious as to what is causing the issue. Have you tested with the 2019 build to see if something changed between builds? 

As for making a debug build its a little involved but not too bad. First is set the `ge -CMAKE_BUILD_TYPE=Debug` mode as you would expect. After that you need to add a few flags to the `em++` stage of the dockerfile. I have only been able to make source map debugging work so `-gsource-map`. You will also need to set a base path flag. I forget exactly what the base path flag is but it will print a warning saying its missing. I set the value to `/` and that was enough for my test server. Finally you need to copy the `openscad.wasm.map` file out of the docker build in order to use it. 

In theory there should be a better way to debug with Chrome and DWARF but I was never able to make it work. If you manage to get that working please let me know as I am very interested to know how.

I'm away from my dev environment this week. When I get back I'll try to build an easy way to enable debug mode. I'm thinking it should be doable using `.env` files to toggle it on and off.

**Comment by t-paul** [comment]
I can try that and upload to http://files.openscad.org/wasm/ - just adding the Debug flag makes it 300MB :smile:.

Slightly related topic, what's your path forward? I'd like to integrate the build with our CI so it's not starting to degrade and break. For that it would be useful to have a base build image with everything except OpenSCAD itself. We do similar things with the Windows builds that are using [MXE images](https://hub.docker.com/r/openscad/mxe-x86_64-gui) for builds on CircleCI ([config](https://github.com/openscad/openscad/blob/6c61ba05d8d61a6276a041b61bf59154df2694b7/.circleci/config.yml#L35-L67)).

**Comment by DSchroer** [comment]
I think that path forward makes sense to me. I want to keep everything in this repo as we transition it and hunt down the bugs in the system. In my view the deno test environment will be quite useful early days because its a lightweight way to automate a browser. 

I'm thinking of going the following way:
1. Split the docker built into two stages, one to build an image with all the dependencies and one to build openscad
2. We can work to merge that second docker part into the core openscad repo
3. We continue building up a web specific test suite here as we work out the kinks in the system
4. We eventually find a way to unify that test system into the core openscad repo

**Comment by t-paul** [comment]
Sounds good. We tested a CGAL patch from https://github.com/marcosscriven/cgaljs which seems to improve things a little bit, but it's still failing in a lot of cases.

**Comment by DSchroer** [comment]
The main issue is that wasm does not support floating point rounding modes. So any method that requires that and then has any asserts will fail. 

We can pull those pathches in as a start but to really fix it there needs to be something bigger.

**Comment by ochafik** [comment]
Wondering whether things break because of the interval arithmetic used to speed up exact kernels (maybe only in code that uses filtered kernels, e.g fast-csg with Epeck, but also hull with Epick, etc).

For Epeck (or filtered kernels based on Gmpq) maybe we could try and add some epsilon safety bounds around intervals returned [here](https://github.com/CGAL/cgal/blob/c44906051814ea085e7bbb035d7f327c6e90a78b/Number_types/include/CGAL/Gmpq.h#L121) + for sibling `Gmqz` class (also see glaring `/* Assume IEEE-754 */` comment in that block 🤣).

For kernels that use double (e.g. Epick), it might just be a matter of fiddling with this `#if 0` block [here](https://github.com/CGAL/cgal/blob/a8e87526348d2d1faa2ea893747314853ee6868d/Number_types/include/CGAL/long_double.h#L123).

Not sure I understand fully how it’s used but think it should only make things slower, not produce wrong results.

```c++
class To_interval ... {
  // -DWASM_EPSILON=0.000001 to be atrociously safe
  std::pair<double, double> operator()( const Type& x ) const {
    const dbl = CGAL::to_double(x);
    return std::make_pair(dbl - WASM_EPSILON, dbl + WASM_EPSILON);
  }
}
```

**Comment by DSchroer** [comment]
That could make sense. I think what is important first is to get a solid debugging experience and hammer this out. Have you been able to get the debug builds working so that your error information is more clear?

**Comment by DSchroer** [comment]
Hey. Couples of updates now that I am back:

1. The build has been split into two files `Dockerfile.base` creates the environment needed and `Dockerfile` has the actual OpenSCAD build in it. I would like to auto push the base image but I am not there yet.
2. I made building debug versions much simpler. Just run `make ENV=Debug` and it will spit out a debug version with source maps enabled. This should make testing easier. Once again I am not a fan of the source map based debugging so if anyone gets DWARF working please let me know. 
3. I added a new test suite that runs most of the examples from the OpenSCAD source (thanks for the `examples.json` file). Without the cgaljs patches I am sitting at 12 passing and 16 failing tests. If someone can run them with the cgaljs patches and report what you get that would be much appreciated. 

My next goal is to start digging in deeper into some of the CGAL errors. Please keep posting any findings that you have here and I am sure we can work through them quick enough.

**Comment by ochafik** [comment]
Thanks for the update @DSchroer ! I didn't manage yet to have chrome pick up the sourcemap (and realized it uses relative paths I'm not serving it yet the deno server anyway), will try again next weekend!

**Comment by ochafik** [comment]
@DSchroer I'm failing to build this now (`make ENV=Debug build`):

```
#51 20.44 make[2]: Entering directory '/src/fc-cache'
#51 20.45   CC       fc-cache.o
#51 20.68   CCLD     fc-cache
#51 21.10 wasm-ld: error: --shared-memory is disallowed by sfnt.c.o because it was not compiled with 'atomics' or 'bulk-memory' features.
#51 21.11 emcc: error: '/emsdk/upstream/bin/wasm-ld -o fc-cache.wasm fc-cache.o ../src/.libs/libfontconfig.a /emsdk/upstream/emscripten/cache/sysroot/lib/pkgconfig/../../lib/libfreetype.a /emsdk/upstream/emscripten/cache/sysroot/lib/pkgconfig/../../lib/libz.a -L/emsdk/upstream/emscripten/cache/sysroot/lib/pkgconfig/../../lib /emsdk/upstream/emscripten/cache/sysroot/lib/pkgconfig/../../lib/libxml2.a -L/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten /emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/crtbegin.o -lGL-mt -lal -lhtml5 -lstubs-debug -lnoexit -lc-mt-debug -ldlmalloc-mt -lcompiler_rt-mt -lc++-mt-noexcept -lc++abi-mt-noexcept -lsockets-mt -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --import-undefined --import-memory --shared-memory --strip-debug --export-if-defined=main --export-if-defined=_emscripten_thread_init --export-if-defined=_emscripten_thread_exit --export-if-defined=_emscripten_thread_crashed --export-if-defined=emscripten_tls_init --export-if-defined=emscripten_current_thread_process_queued_calls --export-if-defined=pthread_self --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__stdio_exit --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_get_base --export=emscripten_stack_init --export=stackSave --export=stackRestore --export=stackAlloc --export=__wasm_call_ctors --export=__errno_location --export=emscripten_dispatch_to_thread_ --export=_emscripten_thread_free_data --export=_emscripten_allow_main_runtime_queued_calls --export=emscripten_main_browser_thread_id --export=emscripten_main_thread_process_queued_calls --export=emscripten_run_in_main_runtime_thread_js --export=emscripten_stack_set_limits --export=emscripten_sync_run_in_main_thread_2 --export=emscripten_sync_run_in_main_thread_4 --export=emscripten_builtin_memalign --export=malloc --export=free --export=saveSetjmp --export=setThrew --export=ntohs --export=htons --export=__dl_seterr --export-table -z stack-size=5242880 --initial-memory=16777216 --no-entry --max-memory=16777216 --global-base=1024' failed (returned 1)
#51 21.13 make[2]: *** [Makefile:524: fc-cache] Error 1
#51 21.13 make[2]: Leaving directory '/src/fc-cache'
#51 21.13 make[1]: *** [Makefile:625: all-recursive] Error 1
#51 21.13 make[1]: Leaving directory '/src'
#51 21.13 make: *** [Makefile:511: all] Error 2
#51 21.13 emmake: error: 'make' failed (returned 2)
------
executor failed running [/bin/sh -c emmake make]: exit code: 1
make: *** [build/.base-image] Error 1
```

**Comment by t-paul** [comment]
I believe that should be covered by the `-s USE_PTHREADS=1` parameter which is patched into the `link.txt` file. Can you see that file being updated?

**Comment by ochafik** [comment]
@t-paul it's there but maybe the same arg is also needed as a compilation flag, not just for linking?

**Comment by DSchroer** [comment]
Hey. Found the issue. I'm still not sure 100% where it came from but I am just verifying a patch. Apply this to the fontconfig lib to fix the build:
```
diff --git a/Makefile.am b/Makefile.am
index 6d4cd32..0dee636 100644
--- a/Makefile.am
+++ b/Makefile.am
@@ -21,10 +21,7 @@
 #  TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 #  PERFORMANCE OF THIS SOFTWARE.
 
-SUBDIRS=fontconfig fc-case fc-lang src \
-	fc-cache fc-cat fc-conflist fc-list fc-match \
-	fc-pattern fc-query fc-scan fc-validate conf.d \
-	its po po-conf test
+SUBDIRS=fontconfig src
 if ENABLE_DOCS
 SUBDIRS += doc
 endif
```

Once I finish verifying it I will push the fix to the repo on my end.

**Comment by DSchroer** [comment]
Nevermind. Failed to get that working. Its something deeper.

**Comment by DSchroer** [comment]
Fix has been pushed. I kept the patch as it made the base build a bit nicer. There was a missing flag in freetype. The build should be fixed now. 

Make sure to delete the `libs/fontconfig` directory.

**Comment by ochafik** [comment]
So, my laptop tries to fly when I do a debug build, **but** on another front... my idea of enlarging the intervals seems to work rather well.

<img width="769" alt="image" src="https://user-images.githubusercontent.com/273860/156887167-f58e78d9-a87c-4d2d-8f89-304ccca622db.png">

([open example](https://tinyurl.com/262hkuu7); the rendering glitch is a bug in the viewer)

I made OpenSCAD to use a single kernel throughout, a simple `CGAL::Cartesian<FilteredNumber<CGAL::Gmpq>>` ([see my FilteredNumber here](https://gist.github.com/ochafik/c22c7b2bc96b78664faf09dbbbb86e52): it's a naive filtered numeric wrapper with very coarse intervals & optional 1-level laziness, although this bit doesn't perform any better yet).

It's slower than `Epeck` (I've enabled `fast-csg` by default, but slowdown is gonna depend on models + what level of laziness we enable) and also bound to be much slower than `Epick`, but also uses a lot less RAM, doesn't need to be made exact at regular intervals to avoid weird performance issues, and... works on WASM so far 🤷‍♂️ (**Edit**: oh, and the generated WASM file is 15% smaller since we don't include instantiations of nefs with multiple kernels).

We also need to replace our usage of Epick with this, I did it for hull and it fixes the PolySet -> Nef import route, but I'm struggling to get rid of Epick for tesselation (might file a bug to CGAL to make their delauney triangulation more kernel-agnostic).

(it's all in my [singleton-kernel](https://github.com/ochafik/openscad/tree/singleton-kernel) branch, in which I'd initially prototyped another bad idea, which was to treat [all numbers as immortal singletons and cache all operations](https://gist.github.com/ochafik/8801e5806a362ab3037ff423289f5348) - spoiler alert: it uses a bit too much memory and isn't faster yet 🤦‍♂️)

I'll probably ask the CGAL guys to add WASM safety intervals to their filtered numeric type. Unsure what the story will be for `Epick` / whether it can be made WASM-compatible, will start taking a look at its implementation.

**Comment by DSchroer** [comment]
Do you have a patch file, branch or PR that I can use in order to work these CGAL changes back into the base image? That way we can supply the fixed builds to people.

**Comment by ochafik** [comment]
@DSchroer I've cleaned up the changes from the branch I mentioned above and will try and get them upstreamed (https://github.com/openscad/openscad/pull/4160), but feel free to have the makefile clone this branch directly in the meanwhile, I'll try and keep it stable-ish :-D

```
# openscad-wasm/Makefile
...
libs/openscad:
	git clone --recurse https://github.com/ochafik/openscad.git --branch filtered-number --single-branch $@
	# branch singleton-kernel mentioned above is messier but is the one I've tested for now
```

**Comment by DSchroer** [comment]
That's what I will do for now. I expected that you would have changed to CGAL as well although I have about 0 understanding of that library internally. 

After testing the state of tests is now at:
```
22 passed; 7 failed;
```

Please let me know when you get your changes merged back and we can target the official codebase again.

**Comment by DSchroer** [comment]
Resolving this issue as Debug builds are available and the exceptions are being worked out. More precise issues should be opened for specific errors.

**Comment by ochafik** [comment]
@DSchroer CGAL makes heavy use of C++ metaprogramming to support generic numeric “kernels” (some of which support pretty much any numeric types). I got lucky that I could just wrap the exact type (from GMP) we’re already using in a more naive (but wasm-robust) way than its Epeck kernel.

I also tried modifying CGAL’s kernels at the places mentioned above (also enlarged CGAL Interval_nt::minimal, etc) but that didn’t get me anywhere 🤷🏻‍♂️

As far as debugging is concerned, I think we still need to crack the loading of source maps + maybe have server.ts serve the sources referred to by said sourcemaps, otherwise debugging won’t be possible.

**Comment by DSchroer** [comment]
I see what you were missing from the debug now. I just pushed a server update to make it simpler to configure. At the moment it works out of the box in chrome: 
![Screenshot from 2022-03-07 09-47-03](https://user-images.githubusercontent.com/3913937/157056981-8dcc921d-e34c-4847-b386-74ae1d4dbe64.png)

Just make sure that you do a full build in debug mode and then run the app once in order to load the source maps. Then in the sources tab you will be able to see the src directory and place breakpoints.

**Comment by DSchroer** [comment]
Note that I was able to drop SharedArrayBuffer requirements. So you can get rid of the service worker in your example now. Should be easier to use.
