### ISSUE TITLE
Codespaces issue

### ISSUE THREAD

**Issue by havana7** [openscad/openscad-wasm#9]
I tried to compile the project on Codespaces but it doesn't work. Do you have any help to give? Thank you.

`ERROR [glib 5/5] RUN chmod +x build.sh; ./build.sh `

**Comment by DSchroer** [comment]
Hey. Do you have more info on what the error is? There are a few things that could have gone wrong in that phase.

**Comment by DSchroer** [comment]
Can you try the build again? I had similar issues with glib and pushed some fixes.

**Comment by havana7** [comment]
I tried but it can't find this repository

fatal: unable to access 'https://gitlab.freedesktop.org/fontconfig/fontconfig.git/': The requested URL returned error: 504
make: *** [Makefile: 78: libs / fontconfig] Error 128

**Comment by DSchroer** [comment]
Looks like they took it down. Replaced with the github version. Any other issues?

**Comment by havana7** [comment]
Yes, There is the same problem with https://gitlab.freedesktop.org/freetype/freetype.git
is not reachable.

`fatal: unable to access 'https://gitlab.freedesktop.org/freetype/freetype.git/': The requested URL returned error: 504
make: *** [Makefile:82: libs/freetype] Error 128`

**Comment by DSchroer** [comment]
Found and fixed that and another checkout issue. I'm hoping it should work now. Please let me know.

**Comment by havana7** [comment]
There is still some problem. :-O

`git clone https://github.com/nih-at/libzip.git --depth 1 --branch master --single-branch libs/libzip
Cloning into 'libs/libzip'...
warning: Could not find remote branch master to clone.
fatal: Remote branch master not found in upstream origin
make: *** [Makefile:101: libs/libzip] Error 128`

With this it should go

`libs/libzip:
	git clone https://github.com/nih-at/libzip.git ${SHALLOW} ${SINGLE_BRANCH_MAIN} $@`

**Comment by havana7** [comment]
But as soon as it gets to this point, here's another error:

`tar xf gmp-6.1.2.tar.lz -C libs
tar (child): lzip: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
make: *** [Makefile:121: libs/gmp-6.1.2] Error 2`

**Comment by DSchroer** [comment]
My last changed should have added the `${SINGLE_BRANCH_MAIN}`
Do you have lzip installed on the machine? That sounds like tar requires it to open lz files but it isn't installed.

**Comment by havana7** [comment]
how do i install lzib on the system?  thank you.

**Comment by havana7** [comment]
Ok, i've installed lzip with:
sudo apt-get install lzip


Now there is another error:

`#12 277.3 make[2]: *** [CMakeFiles/OpenSCAD.dir/build.make:1984: CMakeFiles/OpenSCAD.dir/src/cgalutils-applyops-hybrid-minkowski.cc.o] Error 1
#12 330.4 make[2]: Leaving directory '/build'
#12 330.4 make[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/OpenSCAD.dir/all] Error 2
#12 330.4 make[1]: Leaving directory '/build'
#12 330.4 make: *** [Makefile:130: all] Error 2`

`executor failed running [/bin/sh -c cd ../build && make -j12 VERBOSE=1]: exit code: 2
make: *** [Makefile:42: .image.make] Error 1`

**Comment by DSchroer** [comment]
Ill look into it. Is this coming from the openscad build phase?

**Comment by DSchroer** [comment]
Are you aiming to work on the project or just get the build files? There are pre built versions in the releases page of this repo.

**Comment by havana7** [comment]
> 

Yes, is in the openscad build phase!

**Comment by havana7** [comment]
> Ill look into it. Is this coming from the openscad build phase?

Yes, is in the openscad build phase!

**Comment by havana7** [comment]
> 



> Are you aiming to work on the project or just get the build files? There are pre built versions in the releases page of this repo.

Hi, yes I would like to customize this wonderful work of yours and I would like to do it through Codespace.

Thanks again

**Comment by DSchroer** [comment]
I appreciate that you are interested. I really didnt expect the codebase to rot so fast. 

Can you send me more of the log? My builds are working now and I cant see what the error is from your code snippet.

**Comment by havana7** [comment]
This is the part of the log.

`#12 279.9 em++: error: '/emsdk/upstream/bin/clang++ -target wasm32-unknown-emscripten -DEMSCRIPTEN -D__EMSCRIPTEN_major__=3 -D__EMSCRIPTEN_minor__=1 -D__EMSCRIPTEN_tiny__=13 -fignore-exceptions -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -Werror=implicit-function-declaration -Xclang -iwithsysroot/include/SDL --sysroot=/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/compat -DBOOST_ATOMIC_NO_LIB -DBOOST_FILESYSTEM_NO_LIB -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_REGEX_NO_LIB -DBOOST_SYSTEM_NO_LIB -DCGAL_DEBUG -DCGAL_DISABLE_ROUNDING_MATH_CHECK -DCGAL_USE_CORE=1 -DCGAL_USE_GMPXX -DCGAL_USE_GMPXX=1 -DEIGEN_DONT_ALIGN -DENABLE_CGAL -DENABLE_EXPERIMENTAL -DENABLE_LIBZIP -DNULLGL -DOPENSCAD_DAY=14 -DOPENSCAD_MONTH=6 -DOPENSCAD_NOGUI -DOPENSCAD_OS="Unix" -DOPENSCAD_SHORTVERSION=2022.06.14 -DOPENSCAD_SNAPSHOT -DOPENSCAD_VERSION=2022.06.14 -DOPENSCAD_YEAR=2022 -DSTACKSIZE=8388608 -DUNICODE -DUSE_WASM_COMPATIBLE_KERNELS -D_REENTRANT -D_UNICODE -I/build -I/src -I/src/src -I/src/src/gui -I/src/src/ext/json -I/src/src/ext/lexertl/include -I/src/src/ext/libtess2/Include -isystem /emsdk/upstream/emscripten/cache/sysroot/include/eigen3 -isystem /emsdk/upstream/emscripten/cache/sysroot/include/harfbuzz -isystem /emsdk/upstream/emscripten/cache/sysroot/include/glib-2.0 -isystem /emsdk/upstream/emscripten/cache/sysroot/lib/glib-2.0/include -isystem /emsdk/upstream/emscripten/cache/sysroot/include/freetype2 -isystem /emsdk/upstream/emscripten/cache/sysroot/include/libxml2 -O3 -DNDEBUG -std=c++14 -c /src/src/cgalutils.cc -o CMakeFiles/OpenSCAD.dir/src/cgalutils.cc.o' failed (received SIGKILL (-9))
#12 280.3 make[2]: *** [CMakeFiles/OpenSCAD.dir/build.make:1942: CMakeFiles/OpenSCAD.dir/src/cgalutils.cc.o] Error 1
#12 280.3 make[2]: *** Waiting for unfinished jobs....
#12 348.2 make[2]: Leaving directory '/build'
#12 348.2 make[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/OpenSCAD.dir/all] Error 2
#12 348.2 make[1]: Leaving directory '/build'
#12 348.2 make: *** [Makefile:130: all] Error 2
------
executor failed running [/bin/sh -c cd ../build && make -j12 VERBOSE=1]: exit code: 2
make: *** [Makefile:42: .image.make] Error 1`

**Comment by t-paul** [comment]
That's probably an out-of-memory error. CGAL tends to need quite some memory, so reducing the parallel number `-j12` should fix that issue.

**Comment by havana7** [comment]
Perfect, now it works! thanks
